### ISSUE TITLE
1.12.2 and 1.8 support

### ISSUE THREAD

**Issue by f3f5-dev** [kyngs/LibreLogin#100]
please

**Comment by kyngs** [comment]
Does it not work on Bungee and Velocity?

**Comment by f3f5-dev** [comment]
> Does it not work on Bungee and Velocity?
i mean for spigot servers

**Comment by kyngs** [comment]
1) spigot is not and will not be supported, use paper
2) the plugin requires java 17 or higher, older MC versions don't work with it
3) supporting 8yo versions is just stupid
