### ISSUE TITLE
Add email admin commands

### ISSUE THREAD

**Issue by kyngs** [kyngs/LibreLogin#102]

**Comment by bivashy** [comment]
Can I create PR for this?
I'll implement commands like:
`/librelogin user emailoff <name>`
`/librelogin user setemail <name> <email>`

**Comment by kyngs** [comment]
> Can I create PR for this? I'll implement commands like: `/librelogin user emailoff <name>` `/librelogin user setemail <name> <email>`

Feel free to. Also, please add an email placeholder to the /librelogin user info section.
