### ISSUE TITLE
Add sign out command

### ISSUE THREAD

**Issue by dominik-korsa** [kyngs/LibreLogin#117]
Currently when a player is logged in, they have no way to log out and they will be auto logged-in until the session expires. A log out command would be useful:
- For players with shared IPs
- For server admins to debug the login process
- _more?_
The name of the command has to be decided on, for example: `/logout`, `/signout`, `/sign-out`.
When a player uses the command it should end/revoke the session and either kick the player or send them to the limbo.
A new API event and interaction with existing plugins using the API should be taken into account.

**Comment by kyngs** [comment]
I'm merging this with issue #70
