### ISSUE TITLE
Encountered an exception while communicating with the Mojang API!

### ISSUE THREAD

**Issue by aether1010** [kyngs/LibreLogin#120]
ERROR Encountered an exception while communicating with the Mojang API!
08.08 11:29:21 [服务器] 警告 xyz.kyngs.librelogin.api.premium.PremiumException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
08.08 11:29:21 [服务器] 警告 at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.get玩家FromMojang(AuthenticPremiumProvider.java:169)
......

how to solve this?

**Comment by kyngs** [comment]
If the issue still occurs, then there's an issue between Mojang and your server.

**Comment by aether1010** [comment]
how can i solve this?
