### ISSUE TITLE
Suggestion: Integration of Limbo Support for Authentication Servers

### ISSUE THREAD

**Issue by bivashy** [kyngs/LibreLogin#121]
**Suggestion**:
My thought is to be able to create limbo server authentication just by specifying it in the configuration.

**How it would look like in configuration?**
For example, if you 'wrap' the authentication server in exclamation mark, it turns into a limbo server.
```hocon
# The authentication servers/worlds, players should be sent to, when not authenticated. On Paper, players will be spawned on the world spawn. THIS SERVERS MUST BE REGISTERED IN THE PROXY CONFIG. IN CASE OF PAPER, THE WORLDS MUST EXIST.
limbo=[
    !first!
]
```

**What tools we can use?**
At first LimboAPI comes to mind, but because this plugin is aimed only at Velocity, the only tool I know is NanoLimboPlugin

I think i could try to implement such feature if you will approve it. 

Have a nice day!

**Comment by kyngs** [comment]
I thought about implementing this but didn't have time to do this. 
I don't think that the exclamation mark syntax is necessary, on paper, worlds are also created when they don't exist no matter their syntax. I suppose that the only determining factor should be whether NanoLimboPlugin is installed. 
I suggest that the limbo creation part should be inside the PlatformHandle#getServer, similar to Paper.
