### ISSUE TITLE
mode RANDOM dont work

### ISSUE THREAD

**Issue by TOWUK** [kyngs/LibreLogin#133]
![image](https://github.com/kyngs/LibreLogin/assets/28830162/3552cf72-99be-44ae-b0de-52bd8ab14033)
![image](https://github.com/kyngs/LibreLogin/assets/28830162/2a05f895-993b-4793-a701-9ab36ff723c6)
![image](https://github.com/kyngs/LibreLogin/assets/28830162/584036b0-0f6c-4f63-875d-46bbc5ae6f86)

**Comment by kyngs** [comment]
Prolly your server cannot connect to mojang api

**Comment by TOWUK** [comment]
and fix it
