### ISSUE TITLE
Add a customizable max-character nickname limit

### ISSUE THREAD

**Issue by xiantiao233** [kyngs/LibreLogin#140]
可以自定义玩家名字最长限制

Customizable player name maximum limit

Possibilité de personnaliser la limite maximale de noms de joueurs

**Comment by kyngs** [comment]
Can you clarify? I have no idea what are you asking.

**Comment by xiantiao233** [comment]
就是玩家的名字的长度限制，应该可以配置

**Comment by kyngs** [comment]
Merging this into #196
