### ISSUE TITLE
[enhancement]Administrators can use third-party Mojang APIs

### ISSUE THREAD

**Issue by addpromax** [kyngs/LibreLogin#146]
For well-known reasons, the Mojang API in China has been blacklisted, so that players cannot enter the server by verifying the Mojang API.

**Comment by kyngs** [comment]
While I can change the API URL (api.mojang.com), I cannot change the session server (serssionserver.mojang.com) used for authenticating the players. I suppose you need to change both.

**Comment by addpromax** [comment]
serssionserver.mojang.com Can not be change?

**Comment by kyngs** [comment]
> serssionserver.mojang.com Can not be change?

While I could change the URL on Paper, it is hardcoded in Velocity and BungeeCord.

**Comment by addpromax** [comment]
Thank you.
I will use host to use third party!
