### ISSUE TITLE
Recording in the database who did not register

### ISSUE THREAD

**Issue by DxrkCat** [kyngs/LibreLogin#161]
We were testing a bot attack and the database wrote them in, they have the hash field empty.
Velocity build 290
librelogin 0.18.0

**Comment by kyngs** [comment]
That's the intended behavior, LibreLogin records all players that join. If you want to mitigate this, install an antibot plugin. Librelogin is not an antibot solution.

**Comment by DxrkCat** [comment]
> That's the intended behavior, LibreLogin records all players that join. If you want to mitigate this, install an antibot plugin. Librelogin is not an antibot solution.

Why store users without passwords, they can be cleaned up over time or not stored at all. No ideal anti-bot will be bypassed sooner or later and do you think if I am connected to MySQL it will hold so many records? I believe that you need to clean or not write to the database.
