### ISSUE TITLE
[feature] advanced mysql connect db

### ISSUE THREAD

**Issue by TOWUK** [kyngs/LibreLogin#165]
I saw that there is an extended configuration of database fields in the account, for example, such a configuration is useful for integration with the forum engine, here is an example:
https://discuss.flarum.org/d/11371-minecraft-authme-connect-with-flarum

is it possible to do the same only with your plugin? since I like your plugin a lot more than authme

**Comment by kyngs** [comment]
I'm sorry but this isn't going to be possible as it would only introduce huge unneeded complexity and it still wouldn't work due to the way librelogin stores password.
