### ISSUE TITLE
Test password

### ISSUE THREAD

**Issue by ItsVaidas** [kyngs/LibreLogin#174]
Ability to compare a password with a command. A nice to have feature.
Something like:
/librelogin user test-password Player Password
And it would return:
"Password is correct" or "Password is incorrect"

**Comment by ItsVaidas** [comment]
Without connecting to a database and recreating (figuring out) a login system and all those hashing algorithms, you could just use rcon and check if a password matches. Makes it easier to check if a password is correct.
Or at least integrate an API so that it would be possible to make it with a plugin.

**Comment by kyngs** [comment]
> Without connecting to a database and recreating (figuring out) a login system and all those hashing algorithms, you could just use rcon and check if a password matches. Makes it easier to check if a password is correct.

I'm sorry, but that's just so unsafe I'm not gonna implement this.

> Or at least integrate an API so that it would be possible to make it with a plugin.
LibreLogin already has an API for verifying passwords.

**Comment by ItsVaidas** [comment]
Yea, nvm, found it
