### ISSUE TITLE
Command conflict. Any way to custom the login command.

### ISSUE THREAD

**Issue by Harry-Jing** [kyngs/LibreLogin#184]
In Carpet (a Fabric mod), there is a command called `/log`. When I add this plugin to my proxy server, I can't use the original `/log` command.

Is there any way to customize the command?

**Comment by kyngs** [comment]
Eww this is problematic. The command API I use does not allow for dynamic command adding. Considering librelogin is on the proxy, it should take precedence before the backend server. You should be able to access the backend command using the /modname:log notation.

**Comment by Harry-Jing** [comment]
But how can I know the mod name. It's not the file name.

**Comment by kyngs** [comment]
> But how can I know the mod name. It's not the file name.

Duhh, this is problematic. Can you verify using /carpet:log does not work?
If not, I'll just remove the /log alias, I doubt anyone uses it anyway.

**Comment by Harry-Jing** [comment]
`/carpet:log` doesn't work

**Comment by Harry-Jing** [comment]
I just realised that I can use `/execute at @s run log`.
