### ISSUE TITLE
Exception while communicating with the Mojang API results in disconnects

### ISSUE THREAD

**Issue by LucidAPs** [kyngs/LibreLogin#186]
When there is a failure to connect to the mojang API it kicks everyone from the server, I am seing its part of the premium login feature, please make it so that players are not kicked if the mojang API is acting up or at least make it so that users that have auto-register=false aka are not even using the premium feature are not effected by this.

https://mclo.gs/eSMyma9

**Comment by kyngs** [comment]
This is not possible as it could cause issues. LibreLogin needs to be kept in sync with the Mojang API. The unknown host exception you're experiencing is an issue on your side.
