### ISSUE TITLE
Allow /librelogin user premium|cracked on online players

### ISSUE THREAD

**Issue by HYDeath** [kyngs/LibreLogin#198]
Question:
I use to edit the player information player when in game, I want to for example offline to genuine is rejected does not let me edit.
Requirement:
I would like to enter this command (e.g. /librelogin user premium) to be kicked out of the server for verification directly and automatically just like a normal player who types in the chat bar after executing confirmpremium.

**Comment by gamer50082** [comment]
are you using a translator?
