### ISSUE TITLE
Custom kick message when cracked player logins with premium username

### ISSUE THREAD

**Issue by Cestis** [kyngs/LibreLogin#213]
Hi,
how can I set a custom kick message for cracked players trying to join the server with premium-registered username?

**Comment by kyngs** [comment]
It is not possible, the message is hardcoded in the Minecraft client.

**Comment by Cestis** [comment]
[This plugin](https://www.spigotmc.org/resources/dynamicbungeeauth-premium-command-semi-premium-system-sessions.27480/) supports it.

**Comment by kyngs** [comment]
> [This plugin](https://www.spigotmc.org/resources/dynamicbungeeauth-premium-command-semi-premium-system-sessions.27480/) supports it.

Then they're probably lying tbh. When the Minecraft offline client tries to connect to an online mode server and fails to authenticate, it self-disconnects and sets the message. If the server were to kick the player, you could send the message, however, that's not the case.

**Comment by Cestis** [comment]
> > [This plugin](https://www.spigotmc.org/resources/dynamicbungeeauth-premium-command-semi-premium-system-sessions.27480/) supports it.
> 
> Then they're probably lying tbh. When the Minecraft offline client tries to connect to an online mode server and fails to authenticate, it self-disconnects and sets the message. If the server were to kick the player, you could send the message, however, that's not the case.

I'm currently using it and it works like that. Trying to migrate though due to bad support (and need to switch to velocity).
Perhaps they let all players in and kick with said message when a premium nickname is unauthenticated with mojang?

Also, my destination server is in offline mode.

**Comment by kyngs** [comment]
> > > [This plugin](https://www.spigotmc.org/resources/dynamicbungeeauth-premium-command-semi-premium-system-sessions.27480/) supports it.
> > 
> > 
> > Then they're probably lying tbh. When the Minecraft offline client tries to connect to an online mode server and fails to authenticate, it self-disconnects and sets the message. If the server were to kick the player, you could send the message, however, that's not the case.
> 
> I'm currently using it and it works like that. Trying to migrate though due to bad support (and need to switch to velocity). Perhaps they let all players in and kick with said message when a premium nickname is unauthenticated with mojang?
> 
> Also, my destination server is in offline mode.

What client are you using?

**Comment by Cestis** [comment]
> > > > [This plugin](https://www.spigotmc.org/resources/dynamicbungeeauth-premium-command-semi-premium-system-sessions.27480/) supports it.
> > > 
> > > 
> > > Then they're probably lying tbh. When the Minecraft offline client tries to connect to an online mode server and fails to authenticate, it self-disconnects and sets the message. If the server were to kick the player, you could send the message, however, that's not the case.
> > 
> > 
> > I'm currently using it and it works like that. Trying to migrate though due to bad support (and need to switch to velocity). Perhaps they let all players in and kick with said message when a premium nickname is unauthenticated with mojang?
> > Also, my destination server is in offline mode.
> 
> What client are you using?

Just checked on Prism and Crystal, and you can see said message I configured via the plugin on Crystal Launcher. On Prism it returns just "invalid session" though.

**Comment by d0ddn** [comment]
This is done through the backend server, it is not the proxy that checks the user but the server, after which the server returns a response and the proxy understands what to do with the player (send a custom message)
I saw this implementation at FastLogin, but it is impossible to send a custom message, there you can simply bypass the "player kick"
