### ISSUE TITLE
Allow migration of the player base from "LoginSecurity"

### ISSUE THREAD

**Issue by akbe2020** [kyngs/LibreLogin#214]
https://github.com/lenis0012/LoginSecurity

**Comment by kyngs** [comment]
Already supported

**Comment by akbe2020** [comment]
Thx

**Comment by LcyDev** [comment]
@kyngs Probably should update the wiki https://github.com/kyngs/LibreLogin/wiki/Database-Migration

To avoid confusion.

**Comment by gamer50082** [comment]
You can make a PR with changes for the wiki
