### ISSUE TITLE
A method to add staff users for velocity plugin

### ISSUE THREAD

**Issue by mackdroid** [kyngs/LibreLogin#231]
i use velocity in conjunction with a modded fabric server and do not have the paper plugin install and velocity provides no op mechanism so a alternative would be appreciated

**Comment by kyngs** [comment]
Use a permissions plugin on the proxy such as luckperms.

**Comment by kyngs** [comment]
It does, see the wiki.

**Comment by kyngs** [comment]
???
All staff commands have permission. For the permission list, see the wiki

**Comment by kyngs** [comment]
The fact that Luckperms does not list it does not mean that it does not exist. Enter the permission manually from the list in the wiki.

**Comment by kyngs** [comment]
https://github.com/kyngs/LibreLogin/wiki/Staff-Commands
