### ISSUE TITLE
Question: Does LibreLogin enable protocol encryption for premium users?

### ISSUE THREAD

**Issue by UpYoursMicrosoft** [kyngs/LibreLogin#234]
When I enable the debug option, I see a line in the logs when a premium client joins that isn't there when a cracked client joins.

```
[LibreLogin] [DEBUG] Packet received ENCRYPTION_RESPONSE from null ([redacted])
```

Does this mean that communications with that client are encrypted from that point? I couldn't find the answer searching the repository. Apologies if I missed something.

**Comment by kyngs** [comment]
Yes, as it is mandatory when authenticating premium players.
