### ISSUE TITLE
Version 0.19+ breaks geyser connection

### ISSUE THREAD

**Issue by viktorkozachok21** [kyngs/LibreLogin#241]
![image](https://github.com/kyngs/LibreLogin/assets/44506714/d4037648-278a-4520-9f0e-f450bb761baa)

librelogin - version 0.19+
geyser and floodgate - latest builds

**Comment by viktorkozachok21** [comment]
[2024-04-04-5.log](https://github.com/kyngs/LibreLogin/files/14862833/2024-04-04-5.log)

**Comment by 852DuartePls** [comment]
I came to report the same error, i went back to ver 0.18.3, and solved the Geyser "Read Time Out" problem

**Comment by kyngs** [comment]
> I came to report the same error, i went back to ver 0.18.3, and solved the Geyser "Read Time Out" problem

Please enable debug mode, restart, try to connect from bedrock and send the logs

**Comment by 852DuartePls** [comment]
This is the full log when using 0.19+: https://paste.sh/rEjC9wOM#WcNauv_RVNAo62qVCDHI7KNo

and this is the log when using a previous version: https://paste.sh/ENMnupuH#WNhDOh52gnOjdQR2HTKk2v79

**Comment by viktorkozachok21** [comment]
with debug mode 
[latest.log](https://github.com/kyngs/LibreLogin/files/14892775/latest.log)

**Comment by kyngs** [comment]
I can confirm that I can replicate the issue, gonna try to figure the solution
