### ISSUE TITLE
Russian Translation File

### ISSUE THREAD

**Issue by igorechek06** [kyngs/LibreLogin#242]
I have translated this plugin into Russian and would like to share the translation file. Please consider adding this file to the documentation so that anyone interested can download and use it.

[messages.conf](https://github.com/kyngs/LibreLogin/files/14919795/messages.conf.txt)

**Comment by kyngs** [comment]
Currently, the only centralized place for translations is the relevant channel on the discord supports. Official language handling is planned, but till then I will post it there.
