### ISSUE TITLE
Server Version check

### ISSUE THREAD

**Issue by PanHaskins** [kyngs/LibreLogin#257]
It would be nice to add a check if the player can connect to the lobby after logging in, since limbo supports all versions but the lobby for example doesn't have to and LibreLogin sends the player to the server anyway and doesn't care about anything and then it kicks the player with an "Unable to connect" message.

Possibly add support to the ajQueue/ajQueuePlus plugin.

**Comment by kyngs** [comment]
Out of scope for the plugin; I'm not sure whether this is possible before initiating a connection
