### ISSUE TITLE
The plugin crashes on aarch64 (ARM)

### ISSUE THREAD

**Issue by frantisekhanzlikbl** [kyngs/LibreLogin#258]
Hi!

Currently, when trying to use the plugin with Velocity on an aarch64 machine, the plugin attempts to perform some initialisation, but probably tries to call some native code and crashes. The last log lines look like this:

```
Jun 16 00:32:51 oganesson velocity[1778136]: [00:32:51 INFO] [librelogin]: Loading messages...
Jun 16 00:32:51 oganesson velocity[1778136]: [00:32:51 WARN] [librelogin]: Sorry, but I've needed to reset the totp-show-info message because the process has significantly changed. Here is the original: Please scan the QR code on the map into your 2FA app. For example, Google Authenticator or Authy.
Jun 16 00:32:51 oganesson velocity[1778136]: When you are complete, please execute the /2faconfirm <code> command to finish the process.
Jun 16 00:32:51 oganesson velocity[1778136]: Disconnect to abort.
Jun 16 00:32:56 oganesson systemd[1]: velocity.service: Main process exited, code=dumped, status=31/SYS
```

I'm not sure how much is this in the hands of the plugin, or if it is entirely a fault of some library used, but I figured submitting an issue wouldn't hurt. :)

Please let me know if there is any debugging I can help with.

Version info:

| | |
| - | - |
| LibreLogin | `0.22.0` |
| Velocity | `3.3.0-SNAPSHOT (git-07f1f9e7-b396)` |
| java | `openjdk 21 2023-09-19`<br/>`OpenJDK Runtime Environment (build 21+35-nixos)`<br/>`OpenJDK 64-Bit Server VM (build 21+35-nixos, mixed mode, sharing)` |

**Comment by frantisekhanzlikbl** [comment]
Oh, nevermind, I just tested on an x86_64 machine and the behaviour is identical. Maybe this is not a problem with the arch, but a broken release?

**Comment by kyngs** [comment]
Honestly: the plugin is open-source, if you want to impose restrictions on allowed syscalls, you need to adapt it yourself.

**Comment by frantisekhanzlikbl** [comment]
Fair enough. I'm sorry if I sounded needy; it was not the intention, I've just not put enough effort into properly communicating what I meant to.

Looking into this a bit, it seems like it's not even this plugin that does the chowning, but sponge's HOCON loader. There's probably not much that can be done on the plugin's side.

Thanks for the amazing work on this. It is greatly appreciated. :-)
