### ISSUE TITLE
My friend cant move

### ISSUE THREAD

**Issue by stanowskistano** [kyngs/LibreLogin#260]
He can do everything like putting blocks, attack, jump + w, open doors etc. But he cant walk normlany when he pressing "W"
![2024-06-20_19 08 51](https://github.com/kyngs/LibreLogin/assets/172390237/5b1330e0-07ea-4c82-8e78-e5da26492c20)

**Comment by kyngs** [comment]
Send the logs

**Comment by kyngs** [comment]
stale
