### ISSUE TITLE
Auto-login does not work properly with Forge backend servers.

### ISSUE THREAD

**Issue by alzhahir** [kyngs/LibreLogin#295]
**Here is my setup:**
Proxy network software: Velocity
Limbo server solution: NanoLimbo
Backend servers: Vanilla (PaperMC 1.21.1) and Forge 1.20.1

**Here is the issue:**
When connecting to a vanilla server while auto-login is turned on (at least via Sessions or Premium Auto-login) the player is able to connect successfully. However, connecting to Forge servers via the appropriate Forge client will result in a kick:
```
You're not logged into your Minecraft account. If you're logged into your Minecraft account, try restarting your Minecraft client.
```
Restarting the Forge client does not help. Turning off auto-login however, fixes everything, but it would be nice if we can have it working.

**Comment by kyngs** [comment]
I'm sorry, but forge is not supported. However I think that this is a configuration issue on your forge server, perhaps you forgot to turn online mode off?

**Comment by alzhahir** [comment]
> I'm sorry, but forge is not supported. However I think that this is a configuration issue on your forge server, perhaps you forgot to turn online mode off?

It is running with online mode off. I don't understand why normal login works but auto-login doesn't work, especially since authentication is supposed to happen on the proxy server right?
