### ISSUE TITLE
How do I solve the data migration issue of genuine player change ID?

### ISSUE THREAD

**Issue by 2534905003** [kyngs/LibreLogin#307]
Velocity logs in with LibreLogin, after the genuine player changes his name Is the reason the data is not migrated is because the UUID I obtained is offline?"new-uuid-creator=CRACKED"
How do I solve the data migration issue of genuine player change ID?

**Comment by kyngs** [comment]
The player must've enabled /premium before they changed their name.
You can migrate it manually with /librelogin user migrate oldName newName
