### ISSUE TITLE
Add minimum character check when registering cracked player

### ISSUE THREAD

**Issue by cupang-afk** [kyngs/LibreLogin#44]
my personal reason is there is a cracked player called `a` in my server and its annoy me

i would like to set the minimum to 5 when registering

also, a regex could be useful too for extended purpose _(limiting what character allowed, symbols etc)_

**Comment by kyngs** [comment]
Customizable regex will not be provided, because the plugin will follow Mojang naming scheme. As far as the min character count goes, I may add it into the configuration.
