### ISSUE TITLE
Sugguestion

### ISSUE THREAD

**Issue by fran201921** [kyngs/LibreLogin#47]
You can do Spigot server support?

**Comment by kyngs** [comment]
Spigot won't be supported, because it doesn't have native adventure support.

**Comment by kyngs** [comment]
Use paper, there's really no reason not to

**Comment by fran201921** [comment]
and magma support?

**Comment by kyngs** [comment]
If magma starts natively supporting adventure, then it will work

**Comment by fran201921** [comment]
it no works in magma :( pls fix this

**Comment by kyngs** [comment]
> If magma starts natively supporting adventure (implementing paper API, not Bukkit), then it will work

As I've said, that's an issue on magma's side

**Comment by fran201921** [comment]
ahh ok
