### ISSUE TITLE
Failure to intialize LibreLogin

### ISSUE THREAD

**Issue by Arthurmeade12** [kyngs/LibreLogin#51]
I just installed LibreLogin on my server. The plugin failed to initialize for some reason, looking like logging. LibreLogin did not generate a config folder, so there is neither a config nor a database. 

Plugins:
ActionHealth, Chunky, ChunkyBorder, CoreProtect, CraftBook, CrossplatForms, DeadChest, Essentials, EssentialsChat,  EssentialsGeoIP, floodgate, FreedomChat, Geyser-Spigot, GeyserSkinManager, *LibreLogin, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, Pl3xMap, PlaceholderAPI, ProtocolLib, PurpurExtras, SchematicUpload, SimpleSkills, spark, Terra, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldEditSelectionVisualizer, xaero-map-spigot

[latest.log](https://github.com/kyngs/LibreLogin/files/10915265/latest.log)

Thank you for any help received.

**Comment by kyngs** [comment]
OK, this looks weird. It's quite weird that noone experienced this behavior. Will investigate in a few hours when I'm on a computer.

**Comment by kyngs** [comment]
Your server is in online mode, the plugin should tell you this, it did not due to a coding error. Switch it to offline mode
