### ISSUE TITLE
Players stuck in limbo after logging in

### ISSUE THREAD

**Issue by RealKomander** [kyngs/LibreLogin#55]
I'm using velocity + NanoLimbo1.5 and this issue happens sometimes. Have no idea what to attach here, I'd like to know how is this a librelogin issue in the first place

**Comment by kyngs** [comment]
attach the logs when this happens again

**Comment by RealKomander** [comment]
That was weird, it seemes like it was an issue happening to all the existing players who played before the plugin was added. Anyways, I couldn't reproduce it so there's nothing to fix I guess
