### ISSUE TITLE
Error when joining with Geyser and Floodgate

### ISSUE THREAD

**Issue by TomyGamy** [kyngs/LibreLogin#60]
I tried to join my server using Geyser and Spigot, but I get disconnected each time with the message "connection closed".
When I looked in the server console, i noticed the message "[LibreLogin] [DEBUG] Virtual host for player TomyGamy: null"

The problem doesn't occur when i remove the plugin.

![image](https://user-images.githubusercontent.com/95078425/229334912-72f6c261-e617-4b7e-9c67-4ae884836fe4.png)
![image](https://user-images.githubusercontent.com/95078425/229334918-06eda521-a2f0-4b65-9d31-880fce501a4d.png)

using paper-1.19.4-484

**Comment by kyngs** [comment]
Can you please send the logs?

**Comment by TomyGamy** [comment]
[latest.log](https://github.com/kyngs/LibreLogin/files/11131662/latest.log)

**Comment by TomyGamy** [comment]
So, how is it going?
