### ISSUE TITLE
When using any unknown command player gets kicked

### ISSUE THREAD

**Issue by CralixRaev** [kyngs/LibreLogin#67]
If you use any unknown command in limbo while authentication process (i use NanoLimbo), you get error in velocity console like this:
`A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player <name>`

**Comment by kyngs** [comment]
> If you use any unknown command in limbo while authentication process (i use NanoLimbo), you get error in velocity console like this: `A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player <name>`

This is not an issue with LibreLogin but a limitation on Velocity's side. You can use https://modrinth.com/plugin/unsignedvelocity to make commands unsigned. Also see https://github.com/PaperMC/Velocity/issues/935
