### ISSUE TITLE
JitPack maven repo no longer works since 0.16

### ISSUE THREAD

**Issue by Phoenix616** [kyngs/LibreLogin#73]
Since the 0.16 update the jitpack maven repo no longer works making it incredibly hard to depend on the new update.

**Comment by kyngs** [comment]
For some reason, the build script compilation fails. I don't have the mood to find out why. I will try to change the CI script so it uploads artifacts on my personal repo (repo.kyngs.xyz)

**Comment by kyngs** [comment]
I've updated the relevant wiki page with the new repo and instructions. Once again sorry for the issues.
