### ISSUE TITLE
Improve handling of profile conflicts.

### ISSUE THREAD

**Issue by xism4** [kyngs/LibreLogin#88]
It seems that this happens when the premium player uses the nickname of a non-premium player. Shouldn't the plugin make a verification to avoid this kind of errors?

![image](https://github.com/kyngs/LibreLogin/assets/76608233/aa0f5275-9869-4178-859c-e321d3f673c2)

**Comment by kyngs** [comment]
Perhaps I should implement a more configurable solution to this approach. No ETA tho.

**Comment by xism4** [comment]
> Perhaps I should implement a more configurable solution to this approach. No ETA tho.

Could i know whats your idea? I Will by my self

**Comment by kyngs** [comment]
> > Perhaps I should implement a more configurable solution to this approach. No ETA tho.
> 
> Could i know whats your idea? I Will by my self

I still need to formulate it, thanks for the offer, but I'll do it myself.

**Comment by kyngs** [comment]
@xism4 I've pushed a commit with a proposed solution to this problem: https://github.com/kyngs/LibreLogin/commit/fc764d24570971568da430c1349a93256992b0c7
Is this enough for your use-case?

**Comment by kyngs** [comment]
A solution to which OP has not responded was merged two months ago, marking this as resolved. Reopen if you have any extra clarifications.

**Comment by xism4** [comment]
> A solution to which OP has not responded was merged two months ago, marking this as resolved. Reopen if you have any extra clarifications.

Thanks, was solved.
